version: '3'
services:
  discord-gcal-events-bot:
    #image: mmmaxwwwell/discord-gcal-events-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-gcal-events-bot
    restart: unless-stopped
    volumes:
      - ./secrets:/home/node/secrets
    env_file:
      - ./secrets/.env